### ISSUE TITLE
Greeting from Nimble! 👋 Begin the Challenge Review process

### ISSUE THREAD

**Issue by sleepylee** [kyawlinnthant/nimble-code-test#2]
Hello Kyaw,
Nice to e-meet you 👋 and thanks for your effort on this submission. I'm Trung - Head of Engineering at Nimble. I will be in charge of conducting feedback regarding your code challenge. Feedback will be informed via Issues. 

Kindly keep in mind, it is a bidirectional process, so we would love to hear back from you as well, so please do not hesitate to raise your question/correction in case we missed anything.

If we are aligned on any issue here and you would like to correct them, please go ahead and open a Pull Request per fix, merge it when you feel confident and we will follow up on these fixes 😇

You will have an opportunity to do so moving forward as we create Issues for you to resolve. I hope you find the process enjoyable. Good luck and happy coding 🤘

**Comment by kyawlinnthant** [comment]
Hi Trung,
👋 Nice to meet you too. I've read your feedback via issues and willing to fix them. If I face any misunderstanding on an issue I will question with comment. Kindly, I would like to tell that I will comment my thoughts and solutions before I make a PR. Can I do like that so please?
