### ISSUE TITLE
#1 Don't expose secrets in plaintext, nor git versioning

### ISSUE THREAD

**Issue by sleepylee** [kyawlinnthant/nimble-code-test#3]
Don't expose secrets in plaintext, nor git versioning: https://github.com/kyawlinnthant/nimble-code-test/blob/main/cores/util/src/main/java/com/kyawlinnthant/util/AppConstant.kt.

I found that you left a TODO somewhere, but it seems like you did not address this. Your speed of submission is appreciated, but as a reminder, we would also love to see development driven with the least compromisation, too.

**Comment by kyawlinnthant** [comment]
For this issue, I will move secret keys to `local.properties` and get those keys from BuildConfig file.
For the version control, I will add `/local.properties` in `.gitignore` not to expose secrets via git versioning.

**Comment by kyawlinnthant** [comment]
Fix the issue, making PR with `issue1` branch and merge it. Commit  19a3dcc14940798ea0f9875944c5916e6bd46bee
