### ISSUE TITLE
#3 Token - considered to be sensitive information, is stored in plaintext (DataStore)

### ISSUE THREAD

**Issue by sleepylee** [kyawlinnthant/nimble-code-test#5]
https://github.com/kyawlinnthant/nimble-code-test/blob/main/data/pref/src/main/java/com/kyawlinnthant/pref/PrefDataStoreImpl.kt

As a reminder, DataStore does not encrypt data.

**Comment by kyawlinnthant** [comment]
For this issue, I have two options to solve.

- Android Keystore
- EncryptedSharedPreferences

I will implement `EncryptedSharedPreferences` for this.

**Comment by kyawlinnthant** [comment]
Fix the issue, making PR with `issue3` branch and merge it. Commit  a8f6fa00df84db9b1b8923df1cac6347042440b2
