### ISSUE TITLE
#4 Authenticator - failure case should be treated better

### ISSUE THREAD

**Issue by sleepylee** [kyawlinnthant/nimble-code-test#6]
https://github.com/kyawlinnthant/nimble-code-test/blob/main/data/network/src/main/java/com/kyawlinnthant/network/interceptor/TokenAuthenticator.kt#L49 

let's imagine that a user revoked their sign-in in all devices, authenticator would likely fail and a common UX sense would be to be logout the user, right?

**Comment by kyawlinnthant** [comment]
For this issue, I will add ( logout all devices, login again ) Alert Dialog across all of the application's screens, Tomorrow.

**Comment by kyawlinnthant** [comment]
Fix the issue, making PR with `issue4` branch and merge it. Commit  6736ecc681ed0738c91bfb915f4bba794ea2eb2c
